Hw02
Dante4Rungun/hw-goit-express pull request #3
Opened 2022-11-12 12:23 UTC by Dante4Rungun

2022-11-12 16:17 UTC, Eastvarga commented on models/contacts.js
> +  const contacts = await fs.readFile(path.join(__dirname, 'contacts.json'))
Варто path.join(__dirname, 'contacts.json') дублювання винести окремо як сталу, наприклад. Да і взагалі, метод зчитування з файлу у окремій функції реалізувати та її використовувати для отримання списку контактів

2022-11-12 16:20 UTC, Eastvarga commented on models/contacts.js
> +  return JSON.parse(contacts).filter(contact => contact.id === contactId)
Це погана реалізація, де 404 з "не знайдено" коли ми вказуємо у запиті елемент якого не існує? Треба виправити на коректну логіку.

2022-11-12 16:22 UTC, Eastvarga commented on models/contacts.js
> +  await fs.writeFile(path.join(__dirname, 'contacts.json'), JSON.stringify(newContacts))
Не вірна логіка, та не відповідає ТЗ, потрібно привести до умов завдання!

2022-11-12 16:23 UTC, Eastvarga commented on models/contacts.js
> +  return parsedContacts
Теж не відповідає ТЗ, повернутись має сам доданий об'єкт як результат а не масив

2022-11-12 16:28 UTC, Eastvarga commented on models/contacts.js
> +  return parsedContacts
знову таки, має повернутись сам об'єкт оновлений не масив
до речі краще використати  map( (elem) => { if( elem.id === contactId) { return { ...elem, ...body } } return elem }) для того щоб отримати новий масив з оновленим елементом.
Вам не казали намагатися не використовувати методи котрі мутують данні? Відео з Репетою не дивились?

2022-11-12 16:31 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.json({
краще не використовувати зайву вкладеність та статус відповіді у самому тілі відповіді  body це основні данні котрі передаються з відповіддю.
res.status(200).json(data)

2022-11-12 16:34 UTC, Eastvarga requested changes
Є багато зауважень.
Не виконано умов ДЗ що до відповідей
Немає мінімальної обробки помилок - ви просто їх пересилаєте у відповіді і все, а де сама обробка? Якщо помилка виникла, сервер певним чином повинен її обробити. Що буде якщо файл не буде доступний?

2022-11-14 07:38 UTC, Dante4Rungun commented on models/contacts.js
> +  const contacts = await fs.readFile(path.join(__dirname, 'contacts.json'))
Згоден, дякую, виправив, сам спочатку думав як окрему змінну зробити, а потім просто забув(

2022-11-14 07:40 UTC, Dante4Rungun commented on models/contacts.js
> +  return JSON.parse(contacts).filter(contact => contact.id === contactId)
Виправив, дякую.

2022-11-15 12:44 UTC, Dante4Rungun commented on models/contacts.js
> +  await fs.writeFile(path.join(__dirname, 'contacts.json'), JSON.stringify(newContacts))
Виправив, аппнув валідацію.

2022-11-15 12:44 UTC, Dante4Rungun commented on models/contacts.js
> +  return parsedContacts
Виправив, аппнув валідацію.

2022-11-16 09:56 UTC, Dante4Rungun commented on routes/api/contacts.js
> +  res.json({
Виправив

2022-11-16 09:56 UTC, Dante4Rungun commented on models/contacts.js
> +  return parsedContacts
виправив

2022-11-16 09:56 UTC, Dante4Rungun commented on models/contacts.js
> +  await fs.writeFile(path.join(__dirname, 'contacts.json'), JSON.stringify(newContacts))
виправив

2022-11-16 09:58 UTC, Dante4Rungun commented on models/contacts.js
> +  return parsedContacts
Тут трохи не зрозумів, мова йде про цю строчку?
parsedContacts[parsedContacts.findIndex(contact => contact.id === contactId)] = {id: contactId, name: body.name, email: body.email, phone: body.phone}
Чи про ті моменти де я використовув filter?

2022-11-16 18:51 UTC, Eastvarga commented on models/contacts.js
> +  return parsedContacts
Так тут Ви змінюєте елемент масиву parsedContacts, але це мутація масиву, краще створити новий масив updatedContacs який буде мати в собі оновлений контакт.

2022-11-16 19:12 UTC, Eastvarga commented on models/contacts.js
> +    return utils.createResponse("200", contacts)
Навіщо Ви ускладнюєте собі життя? Не пивинні функції та сервіси знати що твориться у контроллері. Данні запитів та відповідей не повинні просякувати увесь код, бо тоді замість зміни одного метода\функції буде трема міняти усю логіку по всьому коду.

2022-11-16 19:23 UTC, Eastvarga approved these changes

2022-11-16 19:24 UTC, merged