03 mongodb
Dante4Rungun/hw-goit-express pull request #5
Opened 2022-11-17 13:57 UTC by Dante4Rungun

2022-11-17 16:24 UTC, Eastvarga commented on routes/api/contacts.js
А де раут для апдейту поля favorite?

2022-11-17 16:25 UTC, Eastvarga commented on utils/utils.js
> +const getContacts = async (path) => {
Ви повинні видалити ті методи котрі вже не потрібні. Ви вже не працюєте з файлом, а працюєте з БД

2022-11-17 16:26 UTC, Eastvarga commented on validation/validation.js
> +    favorite: Joi.boolean()
чому поле обов'язкове? Де про це щось сказано у ДЗ?

2022-11-17 16:28 UTC, Eastvarga requested changes
Робота не виконана відповідно до ТЗ. Перегляньте ТЗ уважно

2022-11-20 17:13 UTC, Eastvarga commented on controllers/contacts/add.js
> +    if (Object.keys(req.body).length === 0) {
Для чого ця пкрквірка, якщо Ви валідуєте поля запиту у схемі валідатора?

2022-11-20 17:15 UTC, Eastvarga commented on controllers/contacts/remove.js
> +        const result = await Contact.remove({_id: contactId})
невірна відповідь, використайте кращий для цього метод (знайти по айді та видалити)

2022-11-20 17:16 UTC, Eastvarga commented on controllers/contacts/update.js
> +    if (Object.keys(req.body).length === 0) {
Навіщо це, якщо Ви використовуєту валідацію даних?

2022-11-20 17:16 UTC, Eastvarga commented on controllers/contacts/update.js
> +            const result = await Contact.updateOne({ _id: contactId }, req.body, { upsert: true })
Не вірна відповідь на запит, знайдіть кращий метод бо він є!

2022-11-20 17:18 UTC, Eastvarga commented on validation/add.js
> +    favorite: Joi.boolean()
забули додати .optional() до favorite

2022-11-20 17:19 UTC, Eastvarga commented on validation/update.js
> +    name: Joi.string()
для апдейту використовується таж схема що і для створення, Вам не треба дублювати код

2022-11-20 17:20 UTC, Eastvarga requested changes
Є зауваження, треба їх усунути

2022-11-22 11:37 UTC, Dante4Rungun commented on validation/update.js
> +    name: Joi.string()
Не зовсім та сама, в add все окрім favorite - required, в update - ні

2022-11-22 18:22 UTC, closed without merging